### ISSUE TITLE
Saving alternative is writing too many data locations and evaluation locations back to xml

### ISSUE THREAD

**Issue by Tich1212** [HydrologicEngineeringCenter/IRPlugin#23]
Seems to be causing issues with saving the the watershed as well:

run:watching for new scripts in C:\CWMS_TESTING\Plugins\watershed\WS07_HEC_RussianRiver\scripts
writeProject:writing project file C:\CWMS_TESTING\Plugins\watershed\WS07_HEC_RussianRiver\WS07_HEC_RussianRiver.wtrshd
actionPerformed:error in saveProjectAction Error java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.lang.Integer.toString(Unknown Source)
        at java.lang.Integer.toString(Unknown Source)
        at irplugin.EvaluationLocation.writeToXML(EvaluationLocation.java:55)
        at irplugin.IRAlt.saveData(IRAlt.java:76)
        at com.rma.model.AbstractManager.saveData(AbstractManager.java:145)
        at irplugin.IRMain.saveProject(IRMain.java:256)
        at hec2.rts.plugin.PluginProjectListener.projectSaved(PluginProjectListener.java:748)
        at com.rma.model.Project.fireProjectSaved(Project.java:1617)
        at com.rma.model.Project.saveProject(Project.java:2615)
        at com.rma.model.Project.saveProject(Project.java:2545)
        at com.rma.client.BrowserFrame.saveProjectAction(BrowserFrame.java:2604)
        at hec2.rts.client.RtsFrame.saveProjectAction(RtsFrame.java:1796)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at rma.swing.event.ReflectMultiListener.fireMethodCall(ReflectMultiListener.java:122)
        at rma.swing.event.ReflectMultiListener.fireMethodCall(ReflectMultiListener.java:103)
        at rma.swing.event.ReflectMultiListener.actionPerformed(ReflectMultiListener.java:79)
        at com.rma.client.BrowserAction.actionPerformed(BrowserAction.java:209)
        at rma.swing.action.ActionButton.fireEvent(ActionButton.java:477)
        at rma.swing.action.ActionButton.processMouseEvent(ActionButton.java:436)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
managerSavedMessage:no MessageTaker
managerSavedMessage:no MessageTaker
managerSavedMessage:no MessageTaker

**Comment by Tich1212** [comment]
This occurs when there are two or more DataLoations. The alternative has been linked and the alternative is edited and saved following linking.

**Comment by Tich1212** [comment]
Issue is here. The intent was to loop through the names of the existing datalocations and make sure we are not adding the same ones twice. 

https://github.com/HydrologicEngineeringCenter/IRPlugin/blob/1c76812c257f11cb1badd55b2412b5c353d8aa55/src/main/java/alteditor/Controller.java#L201-L208
